version: '3.7'

x-build-args:
  &build-args
  args:
    - USER
    - GROUP
    - UID
    - GID

x-go:
  &go
  working_dir: /app
  stdin_open: yes
  tty: yes

services:
  golocal:
    <<: *go
    image: grpc-tools/golocal
    build: 
      context: ./app
      dockerfile: docker/golocal/Dockerfile
      <<: *build-args
    volumes: 
    - ./app:/app
    - ./.direnv:/go

  gobuild:
    <<: *go
    image: grpc-tools/gobuild
    build: 
      context: ./app
      dockerfile: docker/gobuild/Dockerfile
      <<: *build-args

  prototool:
    image: uber/prototool
    volumes:
      - ./:/work
      - /work/.direnv
      - ./.direnv:/direnv
