version: '3.7'

x-build-args:
  &build-args
  args:
    - USER
    - GROUP
    - UID
    - GID

services:
  golocal:
    image: grpc-tools/golocal
    build: 
      context: ./app
      dockerfile: docker/golocal/Dockerfile
      <<: *build-args
    stdin_open: yes
    tty: yes
    volumes: 
      - ./app:/app
      - ./idl:/idl
      - ./.direnv:/go

  gobuild:
    image: grpc-tools/gobuild
    build: 
      context: ./app
      dockerfile: docker/gobuild/Dockerfile

  prototool:
    image: uber/prototool
    volumes:
      - ./:/work
      - /work/.direnv
      - ./.direnv:/direnv
