version: '3.7'

services:
  echo-server:
    image: grpc-tools/echo-server
    build: 
      context: ./app
      dockerfile: cmd/echo-server/Dockerfile
      target: echo-server
    ports:
      - 8000:8000

  echo-swagger:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/docs/idl/echo/echov1/echo_api.swagger.json
    volumes:
      - ./swagger:/docs
    ports:
      - 8080:8080

  raspi-server:
    image: grpc-tools/raspi-server
    build: 
      context: ./app
      dockerfile: cmd/raspi-server/Dockerfile
      target: raspi-server
    ports:
      - 8001:8001

  raspi-swagger:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/docs/idl/raspi/raspiv1/raspi_api.swagger.json
    volumes:
      - ./swagger:/docs
    ports:
      - 8081:8080

  metrics-server:
    image: grpc-tools/metrics-server
    build:
      context: ./app
      dockerfile: cmd/metrics-server/Dockerfile
      target: metrics-server
    ports:
      - 8002:8002

  exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100

  prom:
    image: prom/prometheus
    volumes:
      - ./monitor/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    depends_on:
      - exporter
      - metrics-server

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prom
