version: '3.7'

services:
  # base go image for running development related tasks
  gobase:
    image: grpc-tools/gobase
    build: 
      context: ./docker/gobase
      dockerfile: Dockerfile
      args:
        - USER
        - UID
        - GID
    volumes:
     - ./app:/app
     - ./.direnv:/go
    working_dir: /app
    stdin_open: yes
    tty: yes

  # prototool the swiss army knife of protobufs
  prototool:
    image: uber/prototool
    volumes:
      - ./:/work
      - /work/.direnv
      - ./.direnv:/direnv

  # serve the swagger doc viewer
  swaggerui:
    image: swaggerapi/swagger-ui
    volumes:
      - ./swagger:/docs
    ports:
      - 8080:8080
