version: '3.7'

services:
  # base go image for running development related tasks
  gobase:
    image: grpc-tools/gobase:devenv
    build: 
      context: ./docker/gobase
      dockerfile: Dockerfile
      args:
        - USER
        - UID
        - GID
    volumes:
     - ./app:/app
     - ./.direnv:/go
    working_dir: /app
    stdin_open: yes
    tty: yes

  # prototool the swiss army knife of protobufs
  prototool:
    image: uber/prototool
    volumes:
      - ./:/work
      - /work/.direnv
      - ./.direnv:/direnv
    stdin_open: yes
    tty: yes

  # serve static api doc json files from ./swagger
  # TODO swagger ui
  docserver:
    image: nginx
    volumes:
      - ./swagger:/usr/share/nginx/html:ro
    ports:
      - 8081:80
