version: '3.7'

services:
  go:
    container_name: go
    build: 
      context: ./docker/go
      dockerfile: Dockerfile
      args:
        - USER
        - UID
        - GID
    volumes:
     - ./app:/app
     - ./.direnv:/go
    working_dir: /app
    stdin_open: yes
    tty: yes

  prototool:
    image: uber/prototool
    volumes:
      - ./:/work
      - /work/.direnv
      - ./.direnv:/direnv
    stdin_open: yes
    tty: yes

  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./swagger/idl/echo/echo_api.swagger.json:/docs/echo_api.swagger.json
    environment:
      - SWAGGER_JSON="/docs/echo_api.swagger.json"
