#!/bin/bash
set -Eeuo pipefail
trap "echo ERR trap fired!" ERR

echo -e "\033[1;37mInstalling development go packages...\033[0m"

# Download various .proto sources.
GO111MODULE=off go get -d -v \
    github.com/gogo/protobuf/... \
    github.com/gogo/googleapis/... \
    github.com/grpc-ecosystem/grpc-gateway/...

go install -v github.com/golang/mock/mockgen

docker-compose -f docker-compose.tools.yml build
    --build-arg username=$(id -un)
    --build-arg user_id=$(id -u)
    --build-arg group=$(id -gn)
    --build-arg group_id=$(id -g)
#- command: docker image prune -f

     