# This file is the cmd/tools/generator's input for generating go backend servers
echo:
  version: v1
  grpc:
    bin: echo-grpc-server
    register: RegisterEchoAPIServer
    implementor: echo.API
  gateway:
    bin: echo-gateway-server
    register: RegisterEchoAPIHandlerFromEndpoint

raspi:
  version: v1
  grpc:
    bin: raspi-grpc-server
    register:  RegisterRaspiAPIServer
    implementor: raspi.API
  gateway:
    bin: raspi-gateway-server
    register: RegisterRaspiAPIHandlerFromEndpoint
